============================= test session starts ==============================
platform linux -- Python 3.11.4, pytest-7.4.0, pluggy-1.0.0
rootdir: /home/user/anaconda3/envs/web_scraping/web_scraping/tests/mismach_correction
collected 1 item

test_004_set_stock_lending_ruiseki_day.py            日付  貸株残
0  2023-09-06   23
           日付    累積始値    累積高値    累積安値  ...  累積逆日歩  累積日歩日数    累積貸株残   累積融資残
0  2023-09-08  2467.0  2497.5  2463.5  ...      0       0      0.0       0
1  2023-09-07  2509.0  2521.5  2492.0  ...      0       0   4600.0  173500
2  2023-09-06  2500.0  2528.5  2498.5  ...      0       0      NaN  146100
3  2023-09-05  2501.5  2518.5  2455.5  ...      0       0  12300.0  155300
4  2023-09-04  2469.0  2491.5  2462.0  ...      0       0  42700.0  154100
5  2023-09-01  2413.0  2463.0  2411.5  ...      0       0  64700.0  136900

[6 rows x 14 columns]
--stock_Lending_day_gyaku_df  2222--
           日付  貸株残
0  2023-09-06   23
--ruiseki_pd  444--
           日付    累積始値    累積高値    累積安値  ...  累積逆日歩  累積日歩日数    累積貸株残   累積融資残
0  2023-09-08  2467.0  2497.5  2463.5  ...      0       0      0.0       0
1  2023-09-07  2509.0  2521.5  2492.0  ...      0       0   4600.0  173500
2  2023-09-06  2500.0  2528.5  2498.5  ...      0       0      NaN  146100
3  2023-09-05  2501.5  2518.5  2455.5  ...      0       0  12300.0  155300
4  2023-09-04  2469.0  2491.5  2462.0  ...      0       0  42700.0  154100
5  2023-09-01  2413.0  2463.0  2411.5  ...      0       0  64700.0  136900

[6 rows x 14 columns]
--日付111--
2023-09-06
--貸株残--
23
F

=================================== FAILURES ===================================
_____________________ testGetGyakuStockLendingDay_normal_1 _____________________

    def testGetGyakuStockLendingDay_normal_1():
        '''
            逆日歩_貸株残から貸株残が不一致の日を抽出
    
            param
            ---------------
            None                                  :
                テスト対象クラス
    
                return
            ---------------
            ruiseki_df                                  : DataFrame
                不一致のみのデータフレーム
        '''
        gt = object_generate()
        # --入力ファイル--
        # ---逆日歩---
        SetStockLendingRuisekiDay_gyaku_df = readDataFrame(
            Test_const.TEST_FILE_PATH,
            Test_const.TEST_004_GYAKUHIBU_READ_FILE_NAME["normal_1"]
        )
        print(SetStockLendingRuisekiDay_gyaku_df)
        # ---累積---
        SetStockLendingRuisekiDay_ruiseki_df = readDataFrame(
                Test_const.TEST_FILE_PATH,
                Test_const.TEST_004_RUIKEI_READ_FILE_NAME["normal_1"]
        )
        print(SetStockLendingRuisekiDay_ruiseki_df)
        # ---正解---
        SetStockLendingRuisekiDay_succes_1_df = readDataFrame(
                Test_const.TEST_FILE_PATH,
                Test_const.TEST_004_CORRECT_ANSWER_FILE_NAME["normal_1"]
        )
    
        # --テスト実施--
        ruiseki_pd = gt.SetStockLendingRuisekiDay(
            SetStockLendingRuisekiDay_ruiseki_df,
            SetStockLendingRuisekiDay_gyaku_df
        )
    
        # 処理結果出力CSVファイル出力
        # --逆日歩不一致日付出力--
>       ruiseki_pd.to_csv(
                Test_const.TEST_FILE_PATH
                + Test_const.TEST_003_RESULT_FILE_NAME["normal_1"]
        )
E       AttributeError: 'NoneType' object has no attribute 'to_csv'

test_004_set_stock_lending_ruiseki_day.py:78: AttributeError
=========================== short test summary info ============================
FAILED test_004_set_stock_lending_ruiseki_day.py::testGetGyakuStockLendingDay_normal_1
============================== 1 failed in 0.53s ===============================
